### ISSUE TITLE
Calling a function to return css within the jss macro?

### ISSUE THREAD

**Issue by ajstrand** [ivanceras/jss#1]
### What I'm trying to do

I'm trying to dynamically insert a bunch of color values into a jss macro
 like this:

```rust
 let css_shell = jss!{
        "body":{
            // function called here
        }
    };
```
my colors are all going to be css custom property strings that look like this:
```css
--custom-color1:#ffdade
```
the basic idea of what I'm trying at the moment with my function is this:

```rust
 let all_colors = vec![]
    for color in colors.iter() {
        let css = format!("--custom-color, {}", color.to_string())
        all_colors.push(css)
     }
    all_colors


```
I'm just not sure how to inject something like the array of values into the jss macro

Is this something that could be done better in vanilla Rust?

**Comment by ivanceras** [comment]
Unfortunately, this is not a use-case I had in mind with this project. Jss aimed to be a simple manipulation of css styles. I might stumbled a case for this in the future, but for now, I'm not going to change the core code to accommodate this use-case.

**Comment by ajstrand** [comment]
@ivanceras no problem! I'll go ahead and figure out an alternative solution for my issue. Thanks the response.
